// File generated from our OpenAPI spec

export type Permission = {
    'name': NameEnum;
};

export enum NameEnum {
    DECI_ACCESS = 'deci:access',
    ERP_ACCESS = 'erp:access',
    SIRENE_ACCESS = 'sirene:access',
    COMMISSION_ACCESS = 'commission:access',
    DOSSIER_CREATE = 'dossier:create',
    DOSSIER_EDIT = 'dossier:edit:*',
    DOSSIER_DELETE = 'dossier:delete',
    DOSSIER_VIEW = 'dossier:view',
    DOSSIER_VIEW_VALIDATION = 'dossier:view:validation',
    DOSSIER_VIEW_VALIDATION_AVIS = 'dossier:view:validation:!avis',
    ERP_CREATE = 'erp:create',
    ERP_EDIT = 'erp:edit:*',
    ERP_EDIT_TITULAIRES = 'erp:edit:titulaires',
    ERP_DELETE = 'erp:delete',
    ERP_VIEW = 'erp:view',
    ORGANISATION_CREATE = 'organisation:create',
    ORGANISATION_EDIT = 'organisation:edit:*',
    ORGANISATION_DELETE = 'organisation:delete',
    ORGANISATION_VIEW = 'organisation:view',
    UTILISATEUR_CREATE = 'utilisateur:create',
    UTILISATEUR_EDIT = 'utilisateur:edit:*',
    UTILISATEUR_EDIT_ROLES = 'utilisateur:edit:roles',
    UTILISATEUR_DELETE = 'utilisateur:delete',
    UTILISATEUR_VIEW = 'utilisateur:view',
    MESSAGE_CREATE = 'message:create',
    MESSAGE_EDIT = 'message:edit:*',
    MESSAGE_DELETE = 'message:delete',
    MESSAGE_VIEW = 'message:view',
    COMMISSION_CREATE = 'commission:create',
    COMMISSION_EDIT = 'commission:edit:*',
    COMMISSION_EDIT_PREFERENCES = 'commission:edit:preferences',
    COMMISSION_DELETE = 'commission:delete',
    COMMISSION_VIEW = 'commission:view',
    ENVELOPPE_CREATE = 'enveloppe:create',
    ENVELOPPE_EDIT = 'enveloppe:edit:*',
    ENVELOPPE_DELETE = 'enveloppe:delete',
    ENVELOPPE_VIEW = 'enveloppe:view',
    EVENEMENT_CREATE = 'evenement:create',
    EVENEMENT_EDIT = 'evenement:edit:*',
    EVENEMENT_DELETE = 'evenement:delete',
    EVENEMENT_VIEW = 'evenement:view',
    DOSSIER_UPDATE_PIECE_JOINTE = 'dossier:update:piece_jointe',
    DOSSIER_WORKFLOW_RAPPORTDETUDE_VISITE_VALIDER = 'dossier:workflow:rapportdetude/visite:valider',
    COMMISSION_GENERATE_CONVOCATION = 'commission:generate:convocation',
    COMMISSION_UPDATE_AVIS = 'commission:update:avis',
    DOSSIER_UPDATE_VALIDATION = 'dossier:update:validation',
    DOSSIER_UPDATE_ARCHIVE = 'dossier:update:archive',
    DOCUMENT_DOSSIER_CREATE = 'document:dossier:create',
    DOCUMENT_DOSSIER_DELETE = 'document:dossier:delete',
    COMMISSION_GENERATE_PROCESVERBAL = 'commission:generate:procesverbal',
    DOCUMENT_MODEL_UPDATE = 'document:model:update',
    FEED_CREATE = 'feed:create',
    FEED_EDIT = 'feed:edit:*',
    FEED_DELETE = 'feed:delete',
    FEED_VIEW = 'feed:view',
    COMMISSION_PASSAGE_ADD_DOSSIER = 'commission:passage:add:dossier',
    SITE_CREATE_FONCTIONNEL = 'site:create:fonctionnel',
    SITE_CREATE_GEOGRAPHIQUE = 'site:create:geographique'
}
